/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chn_halo_util_JniUtils */

#ifndef _Included_com_chn_halo_util_JniUtils
#define _Included_com_chn_halo_util_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chn_halo_util_JniUtils
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chn_halo_util_JniUtils_getKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
